import { StyleSheet, Platform } from 'react-native';
import { colors } from '../../styles/colors';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.gray50 },
  centeredScreen: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 16 },
  errorTitle: { fontSize: 18, fontWeight: 'bold', color: colors.gray800, marginTop: 16 },
  header: { backgroundColor: colors.primary, paddingTop: Platform.OS === 'android' ? 24 : 48, paddingBottom: 16, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center' },
  headerButton: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.2)' },
  headerTitle: { color: colors.white, fontSize: 18, fontWeight: 'bold', marginLeft: 16 },
  statusBadge: { marginLeft: 'auto', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 999 },
  statusBadgeText: { fontSize: 12, fontWeight: '500' },
  mapContainer: { height: 200, width: '100%' },
  map: { flex: 1 },
  markerContainer: { backgroundColor: colors.primary, padding: 8, borderRadius: 999, borderWidth: 2, borderColor: colors.white },
  navigateButton: { position: 'absolute', bottom: 16, right: 16, backgroundColor: colors.white, padding: 12, borderRadius: 999, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2, shadowRadius: 4, elevation: 5 },
  contentPadding: { padding: 16 },
  card: { backgroundColor: colors.white, borderRadius: 12, padding: 16, marginBottom: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 2, elevation: 1 },
  customerHeader: { flexDirection: 'row', alignItems: 'center' },
  customerImage: { width: 64, height: 64, borderRadius: 32 },
  customerInfo: { flex: 1, marginLeft: 16 },
  customerName: { fontSize: 18, fontWeight: 'bold', color: colors.gray800 },
  customerPhone: { fontSize: 14, color: colors.gray500, marginTop: 4 },
  callButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.primary, paddingHorizontal: 16, paddingVertical: 8, borderRadius: 999 },
  callButtonText: { color: colors.white, fontWeight: '500', marginLeft: 8 },
  sectionTitle: { fontSize: 16, fontWeight: 'bold', color: colors.gray800, marginBottom: 12 },
  serviceItem: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: colors.gray100 },
  lastServiceItem: { borderBottomWidth: 0 },
  serviceName: { fontSize: 16, color: colors.gray800, fontWeight: '500' },
  serviceDescription: { fontSize: 14, color: colors.gray500, marginTop: 4 },
  servicePrice: { fontSize: 16, fontWeight: 'bold', color: colors.gray800 },
  totalRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderTopWidth: 1, borderTopColor: colors.gray100, paddingTop: 12, marginTop: 4 },
  totalLabel: { fontSize: 16, fontWeight: 'bold', color: colors.gray800 },
  totalAmount: { fontSize: 20, fontWeight: 'bold', color: colors.primary },
  footer: { padding: 16, borderTopWidth: 1, borderTopColor: colors.gray100, backgroundColor: colors.white },
  primaryButton: { paddingVertical: 14, borderRadius: 8, alignItems: 'center', backgroundColor: colors.primary },
  primaryButtonText: { color: colors.white, fontWeight: 'bold', fontSize: 16 },
  detailRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  detailLabel: { fontSize: 14, color: colors.gray500 },
  detailValue: { fontSize: 14, color: colors.gray800, flexShrink: 1, textAlign: 'right' },
});