import { StyleSheet, Platform } from 'react-native';

import { colors } from '../../styles/colors';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.gray50 },
  centeredScreen: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.gray50 },
  header: { backgroundColor: colors.white, paddingTop: Platform.OS === 'android' ? 24 : 48, paddingBottom: 12, paddingHorizontal: 16, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 4, elevation: 3 },
  headerTitle: { fontSize: 24, fontWeight: 'bold', color: colors.gray800, marginBottom: 16 },
  searchContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.gray100, borderRadius: 8, paddingHorizontal: 12, marginBottom: 12 },
  searchInput: { flex: 1, marginLeft: 8, height: 44, color: colors.gray800 },
  filterScrollView: { marginHorizontal: -16, paddingHorizontal: 16 },
  filterButton: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 999, marginRight: 8, backgroundColor: colors.gray100 },
  activeFilterButton: { backgroundColor: colors.primary },
  filterButtonText: { fontWeight: '500', color: colors.gray700 },
  activeFilterButtonText: { color: colors.white },
  listContentContainer: { padding: 16 },
  jobCard: { backgroundColor: colors.white, borderRadius: 12, padding: 16, marginBottom: 12, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 2, elevation: 1 },
  jobCardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 },
  jobCardCustomer: { flexDirection: 'row', alignItems: 'center' },
  customerImage: { width: 40, height: 40, borderRadius: 20, marginRight: 12 },
  customerName: { fontSize: 16, fontWeight: 'bold', color: colors.gray800 },
  jobTime: { fontSize: 14, color: colors.gray500 },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 999 },
  statusBadgeText: { fontSize: 12, fontWeight: '500' },
  jobCardDetailRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  jobAddress: { flex: 1, marginLeft: 8, color: colors.gray700 },
  divider: { height: 1, backgroundColor: colors.gray100, marginVertical: 8 },
  jobCardFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  jobTotal: { fontSize: 16, fontWeight: 'bold', color: colors.gray800 },
  emptyContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingTop: 40 },
  emptyTitle: { fontSize: 18, fontWeight: '500', color: colors.gray500, marginTop: 16 },
  emptySubtitle: { fontSize: 14, color: colors.gray500, textAlign: 'center', marginTop: 8, paddingHorizontal: 40 },
  clearFilterButton: { marginTop: 16, paddingHorizontal: 16, paddingVertical: 8, backgroundColor: colors.primary, borderRadius: 999 },
  clearFilterButtonText: { color: colors.white, fontWeight: '500' },
});